[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
<<<<<<< HEAD
anchor_amm = "FWS4nCkyRQhov3dZkJkbia3dzr49UvsobQtFAgrde2Ck"

[programs.devnet]
anchor_amm = "FWS4nCkyRQhov3dZkJkbia3dzr49UvsobQtFAgrde2Ck"

=======
anchor_amm = "H9Ynn2dNpmbpJ8SUJEyWwQJLnJ2ZKEmTqun6RCmWpdBM"
>>>>>>> origin/main

[registry]
url = "https://api.apr.dev"

[provider]
<<<<<<< HEAD
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
=======
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
>>>>>>> origin/main
